# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-18 12:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20170307_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateinfo',
            name='project_file_path',
            field=models.FileField(blank=True, max_length=255, upload_to=''),
        ),
    ]
