# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-18 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_candidateinfo_project_file_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateinfo',
            name='cv_path',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
